name: 'E2E Test'

on:
  push:
    branches: [main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning project
        run: git clone --recurse-submodules -j8     
      - name: Docker Compose up
        working-directory:
        run: docker-compose up --build -d
      - name: Run health check
        working-directory:
        run: bash ./wait_for_it.sh
      - name: Install E2E
        run: npm install
        working-directory:
      - name: Run e2e tests
        run: npm run wdio
        working-directory:
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: logs
