version: '3.7'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
    networks:
      - nesjs-network
  frontend:
    container_name: react_frontend
    image: react-frontend:1.0.0
    build:
      context: ./frontend
      target: build-deps
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3001:3000
    networks:
      - nesjs-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  api:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./api
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  ms:
    container_name: nestjs_ms_dev
    image: nestjs-ms-dev:1.0.0
    build:
      context: ./ms
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    networks:
      - nesjs-network
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./ms:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
