name: 'Build and test'

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning project
        run: git clone --recurse-submodules -j8 https://github.com/sasp1/proj.git
      - name: Docker compose up
        run: docker-compose up --build -d
