name: 'Build and test'

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning project
        run: git clone --recurse-submodules -j8 https://github.com/sasp1/proj.git
      - name: Update submodule references
        run: cd proj && git pull --recurse-submodules --jobs=10
      - name: Docker Compose up
        run: cd proj && docker-compose up --build  -d
      - name: Newman install
        run: npm i -g newman
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'
      - name: Run Postman Tests
        run: newman run https://www.getpostman.com/collections/c6ca15eb302ca7b855ec
      # - name: Run Postman tests
      #   # working-directory: ./proj
      #   uses: matt-ball/newman-action@v1.0.2
      #   with:
      #     # work-dir: ./proj
      #     collection: https://www.getpostman.com/collections/c6ca15eb302ca7b855ec
      #     environment: .proj/postman_environment.json
